version: 2.1

orbs:
  cx-cloud-build: cxepi/cx-cloud-build-orb@2.24.0

workflows:
  version: 2
  build-deploy:
    jobs:
      - cx-cloud-build/build-java:
          branch_name: << pipeline.git.branch >>
          sonar_skip: false
          sonar_quality_gate_wait: false
          context:
            - aws-account-devops
            - platform-build
      - cx-cloud-build/publish-docker-container:
          context:
            - aws-account-devops
          requires:
            - cx-cloud-build/build-java
      - cx-cloud-build/publish-helm-chart:
          context:
            - aws-account-devops
          requires:
            - cx-cloud-build/build-java
