# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
var_1: &job_defaults
  docker:
    - image: circleci/openjdk:8-jdk
jobs:
  build:
    <<: *job_defaults
    working_directory: ~/repo
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - setup_remote_docker:  #(2)
          docker_layer_caching: false # (3)
      - run:
          name: Install AWS-CLI
          command: |
            sudo apt-get update && sudo apt-get install -y python-setuptools python python-pip
            sudo pip install awscli
      - run:
          name: aws configure
          command: |
            aws configure set aws_access_key_id $ACCESS_KEY_ID
            aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 432450059541.dkr.ecr.us-east-2.amazonaws.com
      - run:
          name: app checkout
          command: git clone https://www-github3.cisco.com/cxe/cxpp-user-management.git
      - run:
          name: Maven run
          command: |
            cd cxpp-user-management
            mvn clean install

      - deploy:
          name: Build image and push 
          command: |
            docker build -t cxe-pp-user-management .
            docker tag cxe-pp-user-management:latest 432450059541.dkr.ecr.us-east-2.amazonaws.com/cxe-pp-user-management:$CIRCLE_SHA1
            docker push 432450059541.dkr.ecr.us-east-2.amazonaws.com/cxe-pp-user-management:$CIRCLE_SHA1



