apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "cxpp-training-enablement.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ template "cxpp-training-enablement.name" . }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "cxpp-training-enablement.fullname" . }}-environment-properties
data:
  environment.properties: |
{{- range $key, $value := index .Values.files "environment.properties" }}
    {{ $key }} = {{ $value }}
{{- end }}
