apiVersion: v1
kind: Service
metadata:
  name: {{ template "cxpp-training-enablement.fullname" . }}
  labels:
    app: {{ template "cxpp-training-enablement.name" . }}
    chart: {{ template "cxpp-training-enablement.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    {{- if .Values.service.ssl.enabled -}}
    - port: {{ .Values.service.ssl.port }}
      targetPort: {{ .Values.service.ssl.port }}
      protocol: TCP
      name: https
    {{- end }}
  selector:
    app: {{ template "cxpp-training-enablement.name" . }}
    release: {{ .Release.Name }}
